#' \describe{
#'   \item{name}{NA}
#'   \item{name_other}{NA}
#'   \item{supervision_area}{NA}
#'   \item{context}{NA}
#'   \item{direct_access}{NA}
#'   \item{fillup}{NA}
#'   \item{fillup_dry}{NA}
#'   \item{fillup_rainy}{NA}
#'   \item{number_skips}{NA}
#'   \item{capacity}{NA}
#'   \item{y}{NA}
#'   \item{x}{NA}
#'   \item{notes}{NA}
#'   \item{poi}{NA}
#'   \item{lat}{NA}
#'   \item{long}{NA}
#' }
